Repository UMCU-Digital-Health/No_Show, pull requests merged in 2024-07, with the labels that each got.

#106 First version of admin dash
  CHANGELOG.md
  manifest_admin_dash.json
  pyproject.toml
  run/admin_dash.py
Labels: enhancement

#108 Added clinic selection in admin dash
  CHANGELOG.md
  pyproject.toml
  requirements.txt
  run/admin_dash.py
Labels: enhancement, dependencies

#109 Update test data
  CHANGELOG.md
  data/dataset_card.md
  data/raw/data_export.sql
  data/raw/data_prediction.sql
  data/raw/poliafspraken_no_show.csv.dvc
  deploy.sh
  dvc.lock
  notebooks/exploratory_data_analysis.ipynb
  output/dvclive/metrics.json
  output/dvclive/params.yaml
  output/dvclive/plots/metrics/best_score.tsv
  output/dvclive/plots/metrics/mean_precision.tsv
  output/dvclive/plots/metrics/mean_recall.tsv
  output/dvclive/plots/metrics/mean_roc_auc.tsv
  output/dvclive/plots/metrics/std_roc_auc.tsv
  pyproject.toml
  run/config/config.toml.dvc
  src/noshow/preprocessing/load_data.py
  tests/data/test_appointments.json
  tests/test_api.py
  tests/test_model.py
  tests/test_noshow.py
Labels: documentation, enhancement

#112 Fix full name being None bug
  CHANGELOG.md
  pyproject.toml
  src/noshow/api/app.py
Labels: bug

#113 update test appointment data
  tests/data/test_appointments.json
Labels: bug
